version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/{{cookiecutter.project_slug_dashed}}"
    schedule:
      interval: "weekly"

  # Dependabot should be able to pull all Dockerfiles as long as it starts with "dockerfile" (case-insensitive)
  - package-ecosystem: "docker"
    directory: "/{{cookiecutter.project_slug_dashed}}"
    schedule:
      interval: "weekly"
