exclude: 'migrations|.git'
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: '.md'
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black

  - repo: git@github.com:humitos/mirrors-autoflake.git
    rev: v1.3
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-isort]

ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false
