version: '3.6'
services:
    {{ cookiecutter.project_slug }}_db:
        container_name: {{ cookiecutter.project_slug }}_db
        image: postgres:14
        restart: always
        ports:
            - 5532:5432
        volumes:
            - ./database-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: djangodb

    {{ cookiecutter.project_slug }}_web:
        container_name: {{ cookiecutter.project_slug }}_web
        tty: true
        stdin_open: true
        depends_on:
            - "{{ cookiecutter.project_slug }}_db"
        build: 
          context: .
        restart: always
        volumes:
            - .:/web
        ports:
            - 8000:8000
        env_file: .env
        command: bash -c "uvicorn {{ cookiecutter.project_slug }}.asgi:application --host 0.0.0.0 --port 8000"
        environment:
          DATABASE_URL: postgres://postgres:postgres@{{ cookiecutter.project_slug }}_db:5432/djangodb
