version: '3.6'
services:
    web:
        container_name: {{ cookiecutter.project_slug_snaked }}_web
        tty: true
        stdin_open: true
        build:
          context: .
        restart: always
        volumes:
            - .:/web
        ports:
            - 8000:8000
        env_file: .env
        command: bash -c "uvicorn {{ cookiecutter.project_slug_snaked }}.asgi:application --host 0.0.0.0 --port 8000"
{% if cookiecutter.use_celery == "y" %}
    redis:
        container_name: {{ cookiecutter.project_slug_snaked }}_redis
        image: redis:alpine

    celery:
        container_name: {{ cookiecutter.project_slug_snaked }}_celery
        depends_on:
            - web
            - redis
        build:
          context: .
        restart: always
        volumes:
            - .:/web
        env_file: .env
        command: bash -c "celery -A {{ cookiecutter.project_slug_snaked }} worker --beat --loglevel=info"
{% endif -%}
