# Note:
# This Dockerfile is setup if ever production server will not use Docker setup.
# You can also use the updated ubuntu version
FROM ubuntu:22.04

WORKDIR /web

# http://bugs.python.org/issue19846
# > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LANG C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Manila

# extra dependencies (over what buildpack-deps already includes)
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        zlib1g-dev \
        libncurses5-dev \
        libgdbm-dev \
        libnss3-dev \
        libssl-dev \
        libreadline-dev \
        libffi-dev \
        libsqlite3-dev \
        liblzma-dev \
        wget \
        libbz2-dev \
        python3-pip \
        git \
        curl \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Note, this is Python 3.11 stable version; visit and check for updates.
RUN wget https://www.python.org/ftp/python/3.11.5/Python-3.11.5.tar.xz
RUN tar -xf Python-3.11.5.tar.xz
RUN cd Python-3.11.5 && ./configure --enable-optimizations && make && make altinstall

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3.11
COPY . /web

# To use poetry command
ENV PATH="${PATH}:/root/.local/bin"

RUN POETRY_VIRTUALENVS_CREATE=false poetry install

VOLUME ["/web"]
